CATEGORIES = [
    "Electronics",
    "Fashion",
    "Home",
    "Books",
    "Sports",
    "Beauty",
    "Accessories",
]

ORDER_STATUSES = [
    "pending",
    "confirmed",
    "packed",
    "shipped",
    "delivered",
]

DEMO_USERS = [
    {
        "id": "user-admin",
        "name": "Admin User",
        "email": "admin@nagendra.com",
        "password": "Admin@123",
        "role": "admin",
        "phone": "+91 9876543210",
        "addresses": [
            {
                "id": "addr-admin-1",
                "label": "Office",
                "full_name": "Admin User",
                "line1": "12 Admin Plaza",
                "line2": "Suite 502",
                "city": "Bengaluru",
                "state": "Karnataka",
                "postal_code": "560001",
                "country": "India",
                "phone": "+91 9876543210",
                "is_default": True,
            }
        ],
    },
    {
        "id": "user-customer",
        "name": "Demo Customer",
        "email": "customer@nagendra.com",
        "password": "Customer@123",
        "role": "customer",
        "phone": "+91 9988776655",
        "addresses": [
            {
                "id": "addr-customer-1",
                "label": "Home",
                "full_name": "Demo Customer",
                "line1": "44 Lake View Road",
                "line2": "Near Metro Station",
                "city": "Chennai",
                "state": "Tamil Nadu",
                "postal_code": "600028",
                "country": "India",
                "phone": "+91 9988776655",
                "is_default": True,
            }
        ],
    },
]

DEMO_PRODUCTS = [
    {
        "id": "prod-1",
        "sku": "ELEC-1001",
        "name": "Noise Cancelling Headphones",
        "description": "Wireless over-ear headphones with rich bass and 30-hour battery life.",
        "category": "Electronics",
        "price": 7999.0,
        "stock": 18,
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        "rating": 4.7,
        "tags": ["audio", "wireless", "travel"],
        "featured": True,
        "low_stock_threshold": 5,
    },
    {
        "id": "prod-2",
        "sku": "FASH-1002",
        "name": "Minimal Leather Backpack",
        "description": "Durable backpack with laptop sleeve, travel pocket, and water-resistant finish.",
        "category": "Fashion",
        "price": 3499.0,
        "stock": 27,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "rating": 4.4,
        "tags": ["travel", "office", "bags"],
        "featured": False,
        "low_stock_threshold": 6,
    },
    {
        "id": "prod-3",
        "sku": "HOME-1003",
        "name": "Smart Desk Lamp",
        "description": "Adjustable LED lamp with touch controls and warm-to-cool color modes.",
        "category": "Home",
        "price": 2299.0,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "rating": 4.5,
        "tags": ["lighting", "workspace", "smart-home"],
        "featured": True,
        "low_stock_threshold": 4,
    },
    {
        "id": "prod-4",
        "sku": "SPRT-1004",
        "name": "Fitness Smartwatch",
        "description": "Track sleep, workouts, heart rate, and daily activity from one compact wearable.",
        "category": "Sports",
        "price": 5999.0,
        "stock": 22,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        "rating": 4.6,
        "tags": ["fitness", "wearable", "health"],
        "featured": True,
        "low_stock_threshold": 5,
    },
    {
        "id": "prod-5",
        "sku": "BOOK-1005",
        "name": "Deep Work Notebook Set",
        "description": "Premium ruled notebooks designed for focused planning, journaling, and team notes.",
        "category": "Books",
        "price": 899.0,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c",
        "rating": 4.3,
        "tags": ["stationery", "planning", "work"],
        "featured": False,
        "low_stock_threshold": 8,
    },
    {
        "id": "prod-6",
        "sku": "BEAU-1006",
        "name": "Hydrating Skin Care Kit",
        "description": "Complete hydration kit with cleanser, serum, and moisturizer for daily care.",
        "category": "Beauty",
        "price": 1899.0,
        "stock": 11,
        "image": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
        "rating": 4.2,
        "tags": ["skincare", "beauty", "daily-care"],
        "featured": False,
        "low_stock_threshold": 5,
    },
    {
        "id": "prod-7",
        "sku": "ACCS-1007",
        "name": "MagSafe Power Bank",
        "description": "Snap-on fast charging power bank with strong magnetic hold and USB-C input.",
        "category": "Accessories",
        "price": 2499.0,
        "stock": 7,
        "image": "https://images.unsplash.com/photo-1587033411391-5d9e51cce126",
        "rating": 4.5,
        "tags": ["charging", "mobile", "travel"],
        "featured": True,
        "low_stock_threshold": 6,
    },
    {
        "id": "prod-8",
        "sku": "HOME-1008",
        "name": "Air Purifier Mini",
        "description": "Compact purifier for bedrooms and workspaces with HEPA filtration and quiet mode.",
        "category": "Home",
        "price": 4599.0,
        "stock": 9,
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd",
        "rating": 4.1,
        "tags": ["air", "wellness", "home"],
        "featured": False,
        "low_stock_threshold": 5,
    },
]
